-   repo: local
    hooks:
    -   id: flake8-with-builtins
        name: flake8-with-builtins
        entry: flake8 --max-line-length 100
        language: python
        files: \.py$
        additional_dependencies: ['flake8-builtins']
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
        language: python
        language_version: python3
    -   id: name-tests-test
        args: ['--django']
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    sha: v1.0.3
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-f, screen, -iii, -lll, -x, tests, --recursive, .]
        files: .py$

